# Generated by Django 5.0.6 on 2024-07-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
