# Generated by Django 5.0.6 on 2024-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_quantity_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('dozen', 'Dozen'), ('unit', 'Unit')], default='unit', max_length=50),
        ),
    ]
